name: Create S3 Bucket

on: [push]

jobs:
  create-s3-bucket:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your desired AWS region

    - name: Create S3 Bucket
      run: |
        aws s3api create-bucket --bucket nabdit19712015 --region us-east-1
